[2024-07-24T09:54:09.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:54:09.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T06:55:00+00:00 [queued]>
[2024-07-24T09:54:09.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T06:55:00+00:00 [queued]>
[2024-07-24T09:54:09.257+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:54:09.297+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 06:55:00+00:00
[2024-07-24T09:54:09.308+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=746) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:54:09.336+0000] {standard_task_runner.py:64} INFO - Started process 781 to run task
[2024-07-24T09:54:09.339+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T06:55:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmpbei6eg9_']
[2024-07-24T09:54:09.343+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask database_connection
[2024-07-24T09:54:09.492+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T06:55:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:54:10.132+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T06:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T06:55:00+00:00'
[2024-07-24T09:54:10.135+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:54:10.137+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:54:10.306+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:54:10.384+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:54:10.393+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:54:10.395+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:54:10.397+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:54:10.591+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T06:55:00+00:00, execution_date=20240724T065500, start_date=20240724T095409, end_date=20240724T095410
[2024-07-24T09:54:10.774+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:54:10.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
