[2024-07-24T09:52:54.477+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:52:54.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T03:20:00+00:00 [queued]>
[2024-07-24T09:52:54.848+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T03:20:00+00:00 [queued]>
[2024-07-24T09:52:54.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:52:54.957+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 03:20:00+00:00
[2024-07-24T09:52:55.009+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=349) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:52:55.034+0000] {standard_task_runner.py:64} INFO - Started process 390 to run task
[2024-07-24T09:52:55.044+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T03:20:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmp094ih_jb']
[2024-07-24T09:52:55.047+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask database_connection
[2024-07-24T09:52:55.262+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T03:20:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:52:56.072+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T03:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T03:20:00+00:00'
[2024-07-24T09:52:56.074+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:52:56.077+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:52:56.077+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:52:56.174+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:52:56.239+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:52:56.239+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:52:56.240+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:52:56.336+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T03:20:00+00:00, execution_date=20240724T032000, start_date=20240724T095254, end_date=20240724T095256
[2024-07-24T09:52:56.482+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:52:56.599+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:52:56.605+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
