[2024-07-24T05:37:02.074+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T05:37:02.182+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:55:00+00:00 [queued]>
[2024-07-24T05:37:02.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:55:00+00:00 [queued]>
[2024-07-24T05:37:02.202+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T05:37:02.245+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 00:55:00+00:00
[2024-07-24T05:37:02.273+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T05:37:02.277+0000] {standard_task_runner.py:64} INFO - Started process 109 to run task
[2024-07-24T05:37:02.290+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T00:55:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmppgev6401']
[2024-07-24T05:37:02.303+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask database_connection
[2024-07-24T05:37:02.506+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:55:00+00:00 [running]> on host fc934038a502
[2024-07-24T05:37:02.861+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T00:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T00:55:00+00:00'
[2024-07-24T05:37:02.875+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T05:37:02.877+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T05:37:02.878+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T05:37:02.934+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T05:37:02.938+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T05:37:02.939+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T05:37:02.940+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T05:37:03.019+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T00:55:00+00:00, execution_date=20240724T005500, start_date=20240724T053702, end_date=20240724T053703
[2024-07-24T05:37:03.090+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T05:37:03.144+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T05:37:03.149+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-24T09:51:55.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:51:55.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:55:00+00:00 [queued]>
[2024-07-24T09:51:55.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:55:00+00:00 [queued]>
[2024-07-24T09:51:55.852+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:51:55.977+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 00:55:00+00:00
[2024-07-24T09:51:56.024+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:51:56.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T00:55:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmplxh_ysh3']
[2024-07-24T09:51:56.045+0000] {standard_task_runner.py:64} INFO - Started process 140 to run task
[2024-07-24T09:51:56.046+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask database_connection
[2024-07-24T09:51:56.206+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:55:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:51:56.689+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T00:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T00:55:00+00:00'
[2024-07-24T09:51:56.693+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:51:56.695+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:51:56.697+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:51:56.826+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:51:56.828+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:51:56.831+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:51:56.834+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:51:56.966+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T00:55:00+00:00, execution_date=20240724T005500, start_date=20240724T095155, end_date=20240724T095156
[2024-07-24T09:51:57.071+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:51:57.184+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:51:57.192+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
