[2024-07-24T09:51:47.534+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:51:47.848+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:20:00+00:00 [queued]>
[2024-07-24T09:51:47.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:20:00+00:00 [queued]>
[2024-07-24T09:51:47.870+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:51:47.933+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 00:20:00+00:00
[2024-07-24T09:51:47.970+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:51:47.984+0000] {standard_task_runner.py:64} INFO - Started process 109 to run task
[2024-07-24T09:51:48.048+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T00:20:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmpxlhuxxzk']
[2024-07-24T09:51:48.053+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask database_connection
[2024-07-24T09:51:50.728+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T00:20:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:51:53.765+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T00:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T00:20:00+00:00'
[2024-07-24T09:51:53.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:51:53.777+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:51:53.778+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:51:53.869+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:51:53.875+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:51:53.881+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:51:53.882+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:51:53.968+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T00:20:00+00:00, execution_date=20240724T002000, start_date=20240724T095147, end_date=20240724T095153
[2024-07-24T09:51:54.005+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:51:54.111+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:51:54.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
